name: ktlint
on:
  push:
    branches:
      - main
      - develop
      - ktlint
jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: ktlint
        run: ./gradlew ktlintCheck --daemon